kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kibana
  namespace: elastic-system
spec:
  to:
    kind: Service
    name: kibana-kb-http
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
