apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world-backend
spec:
  hosts:
    - hello-world-backend
  http:
  - route:
    - destination:
        host: hello-world-backend
        port:
          number: 8080