apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: pg-tcp
spec:
  listener:
    name: pg-tcp
    protocol: TCP
  upstreams:
  - name: pg-app
    service: postgresql
    port: 5432
  action:
    pass: pg-app

    