kind: Service
apiVersion: v1
metadata:
  name: hello-world-frontend
  labels:
    app: hello-world-frontend
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hello-world-frontend
