kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hello-world-backend
  labels:
    app: hello-world-backend
spec:
  to:
    kind: Service
    name: hello-world-backend
    weight: 100
  port:
    targetPort: 8080
