apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: image-change
spec:
  workspaces:
    - name: source
  params:
    - name: git_url
      type: string
    - name: git_branch
      type: string
    - name: image_repo
      type: string
    - name: image_tag
      type: string
  tasks:
    - name: image-scan
      params:
        - name: image
          value: $(params.image_repo):$(params.image_tag)
        - name: rox_api_token
          value: roxsecrets
        - name: rox_central_endpoint
          value: roxsecrets
        - name: output_format
          value: pretty
      taskRef:
        kind: Task
        name: rox-image-scan
    - name: apply-image-change
      params:
        - name: GIT_USER_NAME
          value: gitea
        - name: GIT_USER_EMAIL
          value: gitea@gitea.com
        - name: GIT_SCRIPT
          value: |
            git clone $(params.git_url)
            cd helm-cd
            git checkout $(params.git_branch)
            sed -i "s|repository:.*$|repository: $(params.image_repo)|" subchart/values.yaml
            sed -i "s|tag:.*$|tag: $(params.image_tag)|" subchart/values.yaml
            cat subchart/values.yaml
            git add .
            git commit -m "updated to new tag"
            git status 
            git push 
      runAfter:
        - image-scan
      taskRef:
        kind: Task
        name: apply-image-change
      workspaces:
        - name: source
          workspace: source
