apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: image-change
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: image-change
      template:
        ref: image-change