kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-image-change
spec:
  to:
    kind: Service
    name: el-image-change
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
