apiVersion: v1
kind: Secret
metadata:
  name: gitea-auth
  annotations:
    tekton.dev/git-0: http://gitea-cicd-tools.apps.90ocp.example.com
type: kubernetes.io/basic-auth
stringData:
  username: gitea
  password: 64506214aa10ef8f76a745bcabfbeb700573aa37