apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: image-change
spec:
  params:
    - name: IMAGE_TAG
      value: '$(body.updated_tags[0])'
    - name: IMAGE_NAME
      value: $(body.docker_url)
